# Site
name: "Ankr Info Brasil, um cluster de brasileiros contribuindo para difundir a Ankr!"
title: "A infraestrutura de nuvem Blockchain para Web 3.0!"
description: "Uma economia de compartilhamento de computação distribuída, fácil, acessível e instantaneamente em todo o mundo!"
meta_description: "Computação instantânea para aplicativos em qualquer lugar!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'admin@ankr.info'
google_analytics: ''
disqus: 'ankrinfo'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  wallison:
    name: Wallison
    display_name: Wallison
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wallisonalvesdeoliveira@gmail.com
    web: https://wallisonalves.com
    twitter: https://twitter.com/wall_is_on
    description: "Admin"

authors:
  yan:
    name: Yan
    display_name: Yan
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: yangm97@gmail.com
    web: https://malha.global/
    twitter: https://twitter.com/yangm97
    description: "Admin"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge
